server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/userservice
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
 
    
  jpa:
    hibernate:
      ddl-auto: update  
  application:
    name: user-service

